### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by lefessan** [NilFoundation/ton-proof-verification-contest#1]
Could you provide more information on the requirements to build this package ?
I have the following issues:
(Ubuntu 20.04 with boost 1.76 and g++ 9.3.0)
* Running `cmake ..` shows some missing dependencies (are they not supposed to be available as sub-modules) ? See the cmake.log file.
* Running `make cli` fails immediately with 
```
~/GIT/NilFoundation/contest/build$ make cli
Scanning dependencies of target cli
Building CXX object bin/cli/CMakeFiles/cli.dir/src/main.cpp.o
In file included from /home/lefessan/GIT/NilFoundation/contest/bin/cli/src/main.cpp:23:
/home/lefessan/GIT/NilFoundation/contest/bin/cli/src/detail/sha256_component.hpp:29:10: fatal error: nil/crypto3/zk/snark/components/hashes/sha256/sha256_component.hpp: No such file or directory
   29 | #include <nil/crypto3/zk/snark/components/hashes/sha256/sha256_component.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [bin/cli/CMakeFiles/cli.dir/build.make:63: bin/cli/CMakeFiles/cli.dir/src/main.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:15991: bin/cli/CMakeFiles/cli.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:15998: bin/cli/CMakeFiles/cli.dir/rule] Error 2
make: *** [Makefile:6675: cli] Error 2
[cmake.log]
```
(https://github.com/NilFoundation/ton-proof-verification-contest/files/6724591/cmake.log)

**Comment by lefessan** [comment]
I forgot to say: I was following the build steps instructions in the README.md file.

**Comment by nemothenoone** [comment]
Hello! 

To make your life easier, we've established a contest-related Telegram chat: https://t.me/joinchat/z0GzOJhnPJAxMTVi. I bet a question like that was already answered in there.

Sincerely yours,
Mikhail Komarov

***@***.***

**Comment by nkaskov** [comment]
@lefessan Hello! It should work now.

**Comment by lefessan** [comment]
Thanks ! It works indeed.
